name: CI
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: https://registry.npmjs.org/
      - name: Build project
        run: npm i && npm run build
      - name: NPM publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.PASS_NPM}}
      - name: NPM GITHUB publish
        uses: actions/setup-node@v1
      - run: echo "//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN" > .npmrc
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN}}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN}}
